### ISSUE TITLE
Moved from Windows/WSL/Ubuntu to RPi 4b Ubuntu 64 and container fails on startup

### ISSUE THREAD

**Issue by smseidl** [rob-luke/emails-html-to-pdf#22]
It's not producing much error details only:
`email2pdf    | standard_init_linux.go:228: exec user process caused: exec format error`

My compose section:
```yml
  email2pdf:
    image: ghcr.io/rob-luke/emails-html-to-pdf:latest
    container_name: email2pdf
    environment:
      - IMAP_URL=xxxx
      - IMAP_USERNAME=xxxx
      - IMAP_PASSWORD=xxxx
      - IMAP_FOLDER=paperless
      - SMTP_URL=xxxx
      - MAIL_SENDER=xxxx
      - MAIL_DESTINATION=xxxx
      - INTER_RUN_INTERVAL=300
      - PRINT_FAILED_MSG='false'
```
